# Generated by Django 6.0.7 on 2026-08-01 14:04

import apps.students.models
import apps.students.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, help_text='JPG, PNG, or WebP - max 2MB.', null=True, upload_to=apps.students.models._student_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.students.validators.validate_photo_file_size]),
        ),
    ]
