from django.db import models


class TimestampedModel(models.Model):
    """
    Abstract base providing created_at/updated_at. Nearly every profile
    model in this project (Student, Parent, Teacher, Staff, ...) wants
    these identically. Left duplicated across Students/Parents/Teachers
    up to this point deliberately - there wasn't yet a case that
    justified the abstraction beyond "these look similar." Bundled into
    EmploymentProfileBase below now that there genuinely is one.
    """

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class EmploymentProfileBase(TimestampedModel):
    """
    Shared shape for "an adult employed by the school." Extracted in
    Phase 6, once Staff's real fields confirmed genuine overlap with
    Teacher (Phase 5) - not designed speculatively beforehand.

    Phase 5 deliberately did NOT extract this: at that point only
    Teacher existed, and guessing Staff's shape in advance risked
    designing the abstraction around a single example that might not
    generalize. Now that Staff is real, the overlap - employee_id,
    date_of_birth, date_joined, phone_number, address, is_active - is
    extracted here. What DIDN'T overlap (Teacher's qualification vs.
    Staff's job_title + employment_type) stays on the concrete
    subclasses, which is exactly where an abstract-base split should
    put it.

    NOTE: this refactor changes zero database columns. Abstract base
    inheritance is a pure Python code-organization tool - Teacher's
    table has the exact same columns whether these fields are declared
    directly on Teacher or inherited from here. No new migration is
    generated by this change (see Testing Instructions below).
    """

    employee_id = models.CharField(max_length=20, unique=True, db_index=True)
    date_of_birth = models.DateField()
    date_joined = models.DateField()
    phone_number = models.CharField(max_length=20, blank=True)
    address = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True