# Generated by Django 6.0.7 on 2026-07-18 09:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0002_teacher_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('PRE_CRECHE', 'Pre-Creche'), ('CRECHE', 'Creche'), ('KINDERGARTEN', 'Kindergarten'), ('PRIMARY', 'Primary'), ('JUNIOR_SECONDARY', 'Junior Secondary'), ('SENIOR_SECONDARY', 'Senior Secondary')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(help_text="Sequence position across the WHOLE school ladder (e.g. 1 for the earliest level up to N for the last) - used to determine the normal 'next' level for promotion.", unique=True)),
                ('has_arms', models.BooleanField(default=False, help_text='Whether this level is split into arms (e.g. JSS1 A/B). Senior Secondary levels conventionally always set this True; Primary/Junior levels vary by school - see requirements doc Section 1.')),
                ('assessment_type', models.CharField(choices=[('SCORE_BASED', 'Score-based (CA + Exam)'), ('SKILL_BASED', 'Skill checklist (e.g. Creche/Nursery)')], default='SCORE_BASED', max_length=20)),
                ('exit_requires_arm_placement', models.BooleanField(default=False)),
                ('promotes_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_from', to='classes.classlevel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ClassArm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'A', 'Science', 'Commerce'.", max_length=50)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_arms_taught', to='teachers.teacher')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arms', to='classes.classlevel')),
            ],
            options={
                'ordering': ['class_level__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pass_percentage', models.PositiveSmallIntegerField(default=40, help_text='Overall percentage required to be promoted.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('promotion_basis', models.CharField(choices=[('THIRD_TERM_ONLY', 'Third term only'), ('CUMULATIVE_ALL_TERMS', 'Cumulative (all terms)')], default='THIRD_TERM_ONLY', max_length=25)),
                ('gatekeeper_pass_mark_mode', models.CharField(choices=[('SAME_AS_OVERALL', 'Same as overall pass percentage'), ('CUSTOM', 'Custom pass mark for gatekeeper subjects')], default='SAME_AS_OVERALL', max_length=20)),
                ('gatekeeper_custom_pass_mark', models.PositiveSmallIntegerField(blank=True, help_text='Only used when gatekeeper_pass_mark_mode is CUSTOM.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gatekeeper_logic', models.CharField(choices=[('ANY_ONE_FAILS', 'Failing ANY ONE gatekeeper subject forces a repeat'), ('ALL_MUST_FAIL', 'ALL gatekeeper subjects must be failed to force a repeat')], default='ANY_ONE_FAILS', max_length=20)),
                ('skill_based_promotion_mode', models.CharField(blank=True, choices=[('AUTOMATIC', 'Automatic (age/term-based, no criteria)'), ('CHECKLIST_DERIVED', 'Derived from the skill checklist'), ('ADMIN_JUDGMENT', 'Admin judgment call, no formula')], max_length=20)),
                ('class_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_policy', to='classes.classlevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True)),
                ('is_repeat', models.BooleanField(default=False, help_text='Whether this enrollment represents repeating the same level again.')),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_enrollments_assigned', to=settings.AUTH_USER_MODEL)),
                ('class_arm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='classes.classarm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='students.student')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='classes.classlevel')),
            ],
            options={
                'ordering': ['-assigned_on'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('student',), name='unique_current_enrollment_per_student')],
            },
        ),
        migrations.AddConstraint(
            model_name='classarm',
            constraint=models.UniqueConstraint(fields=('class_level', 'name'), name='unique_arm_name_per_level'),
        ),
    ]
