# Generated by Django 6.0.7 on 2026-07-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionpolicy',
            name='cumulative_method',
            field=models.CharField(choices=[('SIMPLE_AVERAGE', 'Simple average across all terms'), ('RECURSIVE_BROUGHT_FORWARD', 'Recursive Brought-Forward average (each term averaged with the running cumulative)')], default='SIMPLE_AVERAGE', help_text="Only relevant when promotion_basis is CUMULATIVE_ALL_TERMS. RECURSIVE_BROUGHT_FORWARD matches a real school's actual computation (Elon College): each new term's score is averaged with the running cumulative from before it, which mathematically weights the most recent term more heavily than a flat average across all terms would. The actual computation is implemented in the Examinations phase, once real term-by-term scores exist to combine - this field only records the CHOICE.", max_length=25),
        ),
    ]
