# Generated by Django 6.0.7 on 2026-07-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_promotionpolicy_cumulative_method'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionpolicy',
            name='gatekeeper_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects where failing can force a repeat regardless of overall percentage.', related_name='gatekeeper_for_policies', to='subjects.subject'),
        ),
    ]
