# Generated by Django 6.0.7 on 2026-07-22 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_promotionpolicy_gatekeeper_subjects'),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classenrollment',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_enrollments', to='terms.academicsession'),
        ),
    ]
