# Generated by Django 6.0.7 on 2026-07-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_classenrollment_academic_session'),
        ('teachers', '0002_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='class_teacher',
            field=models.ForeignKey(blank=True, help_text='Only meaningful when this level has NO arms (has_arms=False).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_levels_taught', to='teachers.teacher'),
        ),
    ]
