# Generated by Django 6.0.7 on 2026-07-20 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_promotionpolicy_cumulative_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text="e.g. 'WAEC 9-point scale', optional.", max_length=100)),
                ('class_level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scale', to='classes.classlevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="e.g. 'A1', 'B2', 'A', 'F9'.", max_length=10)),
                ('description', models.CharField(blank=True, help_text="e.g. 'Excellent'.", max_length=50)),
                ('min_percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_percentage', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grading_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='subjects.gradingscale')),
            ],
            options={
                'ordering': ['-min_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text="e.g. 'MTH', 'ENG'.", max_length=20)),
                ('assessment_type', models.CharField(choices=[('SCORE_BASED', 'Score-based (CA + Exam)'), ('SKILL_BASED', 'Skill checklist (e.g. Creche/Nursery)')], default='SCORE_BASED', help_text='Primary mode hint for defaults and grading policy - does NOT prevent this subject from having both numeric components and a skill checklist at the same time.', max_length=20)),
                ('computation_method', models.CharField(choices=[('SUM_COMPONENTS', 'Sum components (CA total + Exam total)'), ('AVERAGE_CA_AND_EXAM', 'Average CA components, average with Exam components')], default='SUM_COMPONENTS', help_text="How CA and Exam components combine into a final score. SUM_COMPONENTS: sum all CA component maxes + sum all Exam component maxes (e.g. CA=40 + Exam=60 = 100 - confirmed real usage: AOS Montessori). AVERAGE_CA_AND_EXAM: average the CA components together, average the Exam components together, then average those two averages (confirmed real usage: Elon College's T1/T2/T3 averaged, then averaged with the Term Exam). The actual per-student computation using this setting is implemented in the Examinations phase, once real scores exist to combine - this field only records the CHOICE.", max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('class_levels', models.ManyToManyField(blank=True, related_name='subjects', to='classes.classlevel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(help_text="e.g. 'Can identify 5 colors'.", max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_items', to='subjects.subject')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'CA1', 'CA2', 'Exam'.", max_length=50)),
                ('component_type', models.CharField(choices=[('CA', 'Continuous Assessment'), ('EXAM', 'Exam')], max_length=10)),
                ('max_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_components', to='subjects.subject')),
            ],
            options={
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'name'), name='unique_component_name_per_subject')],
            },
        ),
    ]
