# Generated by Django 6.0.7 on 2026-08-14 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classlevel_class_teacher'),
        ('subjects', '0001_initial'),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='classes.classlevel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.subject')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='terms.term')),
            ],
            options={
                'ordering': ['class_level__order', 'subject__name', 'order'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'class_level', 'name'), name='unique_topic_name_per_subject_level')],
            },
        ),
    ]
