# Generated by Django 6.0.7 on 2026-07-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('classes', '0004_classenrollment_academic_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='class_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='classes.classlevel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='class_arm',
            field=models.ForeignKey(blank=True, help_text='Null when class_level.has_arms is False.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='classes.classarm'),
        ),
    ]
